name: valis_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10           # VALIS supports Python 3.9 or 3.10
  - openjdk>=11           # for Bio-Formats (Java runtime)
  - maven                 # for Bio-Formats (needed to build Bioformats jar index)
  - openslide             # OpenSlide library for certain slide formats
  - openslide-python      # Python bindings for OpenSlide
  - pyvips                # Python bindings for libvips (includes libvips)
  - scikit-image          # image processing (VALIS uses it for features)
  - numpy                 # numerical library
  - pandas                # for data processing and CSV handling
  - matplotlib            # for visualization
  - pillow                # for image processing
  - opencv                # for feature detection and image processing
  - pip                   # include pip to install valis-wsi
  - pip:
    - valis-wsi==1.1.0    # VALIS package (version 1.1.0)
    - tifffile            # for handling OME-TIFF files
    - scyjava             # required for Bio-Formats Java interop
